version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # MailHog web interface
      - "1025:1025" # MailHog SMTP server

  mailgw:
    image: ngmaibulat/mailgw
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/mailgw/config:/opt/mailgw/config
      - /opt/mailgw/queue:/opt/mailgw/queue
      - /opt/mailgw/log:/opt/mailgw/log
    container_name: mailgw
