version: '3.8'

services:
  db-migrator:
    image: ngmaibulat/db-migrator:latest
    depends_on:
      - db
    networks:
      - mailgw
    environment:
      DB_DRIVER: ${DB_DRIVER}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

networks:
  mailgw:
    external: true
